name: Sync to Gitee
on:
  push:
    branches: [ main ]
  workflow_dispatch:    # 支持手动触发
  schedule:
    - cron: "0 0 * * *"  # 每日 UTC 0 点同步[2,7](@ref)
  repository_dispatch:    # 通过 API 触发
    types: [ manual-sync ]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub code
        uses: actions/checkout@v4

      - name: Setup Gitee SSH Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan gitee.com >> ~/.ssh/known_hosts

      - name: Set Git Identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push to Gitee Mirror
        run: |
          git remote add gitee git@gitee.com:lzhnssc/awesome-embodied-ai-job-mirror.git
          git push gitee main --force